### ISSUE TITLE
Conflict with Cardbook 10.7

### ISSUE THREAD

**Issue by michelRenon** [michelRenon/mrc_compose#35]
Review from Nick2222:
Conflict with Cardbook 10.7 - autocomplete address do not work

**Comment by biva** [comment]
See also https://github.com/CardBook/CardBook/issues/218

**Comment by michelRenon** [comment]
Now that it is compatible with TB60, I can take care of other improvements and link with Cardbook is one of them. 
Keep in mind that I develop that on my free time, so it's difficult to define any timeline.
And maybe that next TB (61+) will change foundations for addons (webextension ? restartless ?) that will delay those improvements.
Thanks

**Comment by biva** [comment]
Great, thanks :)

I see that MailMerge (https://addons.mozilla.org/fr/thunderbird/addon/mail-merge/) from Alexander Bergmann (@abergmann ?) is able to look into a variety of address book, including CardBook, and that he collaborated with CardBook: maybe he can give us and MRC some advice? I see his email is myaddons@gmx.de

And I know that @CardBook would like to make its addon compatible with yours.

**Comment by biva** [comment]
Hello @michelRenon : any update on the compatibility with cardbook? It would be really great if these 2 amazing add-ons would work together. The issue on cardbook is now on Gitlab: https://gitlab.com/CardBook/CardBook/issues/218

**Comment by biva** [comment]
Hello @michelRenon : @cardbook developper [tells me that he modified cardbook according to your needs](https://gitlab.com/CardBook/CardBook/issues/218#note_88284213). Is it enough? Are you able to make MRC compose compatible with cardbook? Thank you!

**Comment by biva** [comment]
Hello @michelRenon : any chance to make progress on this issue with cardbook? I'm available to test if needed.

**Comment by michelRenon** [comment]
Sorry for the delay, but I had big professional changes : I still don't have free time to work on MRC Compose. Maybe in 1 or 2 months.

**Comment by biva** [comment]
Hello @michelRenon Would you have more time to look for a solution? I miss your MRC!!
Thank you very much :)

**Comment by marcoagpinto** [comment]
I miss the add-on too :( 

Buaaaaaaaaaaaaaaaaaaaa

**Comment by ovari** [comment]
> I [Philippe Vigneau] have modified CardBook according to Michel wishes... so it's up to him now...
https://gitlab.com/CardBook/CardBook/issues/218#note_88284213

> I [Michel Renon] still don't have free time to work on MRC Compose. Maybe in 1 or 2 months.
https://github.com/michelRenon/mrc_compose/issues/35#issuecomment-420076951

Could you please provide an update?

Thank you

**Comment by mmalmeida** [comment]
Following. I just found out about Cardbook and it looks very promising.
MRC compose is also an amazing tool. Would love to see their efforts combined! @michelRenon do you need anything else to make this happen?

**Comment by ovari** [comment]
@michelRenon could you please advise an ETA for CardBook compatibility or otherwise? Thank you

**Comment by biva** [comment]
Hi @michelRenon Do you still plan to update your addon? I'd really like to see it back!
Thank you in advance!!

**Comment by ovari** [comment]
Can this be closed as fixed?

## [MRC Compose](https://addons.thunderbird.net/addon/mrc-compose/)
### About this Add-on
About version 2.0.0 :
* Compatibility with Thunderbird 68
* Can search in 'Cardbook' address books
* In preferences, show type of each address book : 'Thunderbird', 'LDAP', 'Cardbook'

**Comment by biva** [comment]
Yihaaa, thank you so much!! It works perfectly :)

**Comment by ovari** [comment]
Interested parties may like to follow:
Bug 440377 Redesign recipients address fields (To, Cc, Bcc) as single-line input fields for multiple comma separated addresses - not one line/row per address
https://bugzilla.mozilla.org/show_bug.cgi?id=440377

**Comment by michelRenon** [comment]
Cardbook support has been added in MRC Compose 2.0
