### ISSUE TITLE
Add "total contacts:" + "SORT" button

### ISSUE THREAD

**Issue by marcoagpinto** [michelRenon/mrc_compose#38]
Could you implement a textbox gadget that shows the total number of recipients inserted?
This would be useful because ISPs usually limit the number of contacts in each send. For example, my ISP only lets send a maximum of 50 e-mails at a time.

Also, a SORT button to alphabetically sort the recipients in the To:, Cc: and Bcc:
This is useful because one could more easily check in long recipients lists if we didn't forget one.

**Comment by michelRenon** [comment]
Hi Marco,
thanks for your suggestions, they are good ideas !
I'll look at them as soon as I have enough time.
Just to ease bug tracking, can you please split them (the current for "total contacts" and create one for "add sort button")

**Comment by michelRenon** [comment]
splitted: #42 and #41
