### ISSUE TITLE
MRC Compose currently lack of es-ES locale

### ISSUE THREAD

**Issue by newton181** [michelRenon/mrc_compose#46]
Hello, i'm translating MRC Compose to spanish, i've used utf8 for all files. When i finish help files i'll share here if you want add them.

![1](https://user-images.githubusercontent.com/39416322/40250042-ab083d8a-5a9a-11e8-9f5e-91ea340d4ad9.PNG)
![2](https://user-images.githubusercontent.com/39416322/40250055-b3126d0c-5a9a-11e8-8d11-271be1a893be.PNG)
![3](https://user-images.githubusercontent.com/39416322/40250060-b4336614-5a9a-11e8-8800-b7965228545e.PNG)
![4](https://user-images.githubusercontent.com/39416322/40250061-b5675360-5a9a-11e8-8808-acfdfed8b632.PNG)
![5](https://user-images.githubusercontent.com/39416322/40250062-b651cb2a-5a9a-11e8-98f2-3d97f285e5f1.PNG)

**Comment by michelRenon** [comment]
Hi,
Thank you for your work ! I'll happy to add them. 
For your information :
- I created #47  : I'll update file 'help_mode.txt', and you'll have to update the spanish translation
- There is some ongoing work to add compatibility with Cardbook : it'll also change translation files. But as it'll be in some weeks, I'll keep you updated.
Cheers,
Michel
