### ISSUE TITLE
problem with lists and To: field (bug)

### ISSUE THREAD

**Issue by droumanet** [michelRenon/mrc_compose#57]
Tested with To: field. No bug on Copy to: field.
Use 2 list (more than 5 names). 
1) search for first list, validate [Enter]
2) search for second list, validate : warning message is present but the To: field isn't visible.
![2018-09-04 22_57_19-window](https://user-images.githubusercontent.com/24438463/45101923-d11fce00-b12c-11e8-9296-96e1c0db1fc6.png)

Settings are by default

**Comment by droumanet** [comment]
After more investigations, **it seems that the TO: field couldn't have more than one line**, while Copy To: could show 4 lines.
If I activate Reply To: field (and other fields like group, follow, ...) they could display my lists without problem. Only To: have this problem ► not a problem with the warning

**Comment by droumanet** [comment]
![image](https://user-images.githubusercontent.com/24438463/45221850-0d7d3680-b2b3-11e8-894f-1c9886393d4c.png)

**Comment by michelRenon** [comment]
Corrected by changing the css rules of gear icon, in commit 91359717e4e2819020a1d95c947560135e3607b5.
Will be integrated in version 1.9.1.
