### ISSUE TITLE
Disable spellcheck in fields

### ISSUE THREAD

**Issue by michelRenon** [michelRenon/mrc_compose#58]
From a review in addons.thunderbird.net:
https://addons.thunderbird.net/fr/thunderbird/addon/mrc-compose/reviews/1156941/

when I enter the contact's name into the "To:" field, the surname is underlined with a wavy red line - I don't wish to spellcheck this (and I already have spellchecking turned off everywhere in thunderbird) - so is there a way to disable the spellchecking of the names?

**Comment by newton181** [comment]
In my newst branch this was fixed, same some spanish strings in help files.

**Comment by michelRenon** [comment]
Thanks for your contribution.
I'll merge your code in the next few days, most probably this weekend.

**Comment by michelRenon** [comment]
Merged !
thanks again for your contribution.
