### ISSUE TITLE
Compatibility issue with Thunderbird 68

### ISSUE THREAD

**Issue by droumanet** [michelRenon/mrc_compose#62]
Hello,
I've just giving a try to Thunderbird 68 and MRC Compose has been desactivated (tagged as incompatible with the version).
Any solution?

Thanks
David

**Comment by dugite-code** [comment]
There has been some work in order to reach TB68 compatibility, however there are still a few show stopping issues to iron out yet.

Please refer to the [dev_tb68](https://github.com/michelRenon/mrc_compose/tree/dev_tb68) branch to see the progress

**Comment by ovari** [comment]
Can this ticket be closed as fixed as version 2+ of this add-on is compatible with Thunderbird 68 and is showing on [ATN](https://addons.thunderbird.net/addon/mrc-compose/)? Thank you

**Comment by michelRenon** [comment]
MRC Compose 2.0 is compatible TB68
