### ISSUE TITLE
Adding a space doesn't show any result in autocomplete

### ISSUE THREAD

**Issue by biva** [michelRenon/mrc_compose#66]
The autocomplete feature (or search feature?) does not show any result if I add a space after a name.
- For example, if I look for Johnny Depp in my contacts, I find him if I type `johnny`:
 ![image](https://user-images.githubusercontent.com/9964305/70040403-cbc56380-15bb-11ea-8a2f-e9a209c15bbb.png)
- But if I type `johnny depp` (because I have a lot of Johnny in my address book), I don't find any result:
![image](https://user-images.githubusercontent.com/9964305/70040654-34acdb80-15bc-11ea-80af-f5e3712f7706.png)
- The workaround is to type `johnnydepp` (without space), but it's not intuitive:
![image](https://user-images.githubusercontent.com/9964305/70040863-7fc6ee80-15bc-11ea-8ed6-727973ae5489.png)

Would it be possible to suggest results even if we put a space?

**Comment by biva** [comment]
Hello @michelRenon 
do you experience the same? Any solution?

**Comment by michelRenon** [comment]
Cardbook uses a transformed string to build indexes and perform searches.
MRC Compose now uses same behavior when searching in cardbook.
Fix will be available in 2.0.4
