### ISSUE TITLE
Popularity does not work with Cardbook

### ISSUE THREAD

**Issue by biva** [michelRenon/mrc_compose#68]
Hello @michelRenon ,
I'm using MRC and Cardbook and the autocomplete feature does not sort the contacts by popularity. Instead, the sorting is not even alphabetical. Do you experience the same? Do you have a solution?

My setup:
TB 68.4.1
Cardbook 43.5
MRC 2.0.2
(issue reported at Cardbook as well: https://gitlab.com/CardBook/CardBook/issues/799)

**Comment by michelRenon** [comment]
As Cardbook has it's own way to store popularity, I had to update MRC Compose to handle it.
Now each searched cardbook card has the popularity based on the max popularity of its emails.
And if a cardbook card has several emails, emails are sorted by their own popularity.
Fix will be available in 2.0.4
